experiment:
  backend: [tensorflow, pytorch]
  data_config:
    strategy: fixed
    train_path: ../data/{0}/Train.tsv
    validation_path: ../data/{0}/Val.tsv
    test_path: ../data/{0}/Test.tsv
    side_information:
      - dataloader: WordsTextualAttributesPreprocessed
        all_item_texts: ../data/{0}/all_item_texts.npy
        all_user_texts: ../data/{0}/all_user_texts.npy
        embed_vocabulary: ../data/{0}/embed_vocabulary.npy
        item_to_user: ../data/{0}/item_to_user.npy
        item_to_user_to_item: ../data/{0}/item_to_user_to_item.npy
        user_to_item: ../data/{0}/user_to_item.npy
        user_to_item_to_user: ../data/{0}/user_to_item_to_user.npy
  dataset: Digital_Music
  top_k: 50
  evaluation:
    cutoffs: [ 10, 20, 50 ]
    simple_metrics: [Recall, MSE]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.RMG:
      meta:
        save_recs: False
        validation_metric: MSE
        validation_rate: 1
        verbose: True
      d: 0.2
      epochs: 400
      batch_size: 256
      be: 16
    external.GCMC:
      meta:
        save_recs: False
        validation_metric: MSE
        validation_rate: 1
        verbose: True
      lr: 0.001
      epochs: 20
      batch_size: 128
      batch_eval: 512
      factors: 64
      conv_size: 64
      dense_size: 64
      n_conv: 1
      n_dense: 1
      relations: (1,2,3,4,5)
      num_basis: 2
      dropout: 0.1
      acc: stack
