experiment:
  backend: [tensorflow]
  data_config:
    strategy: fixed
    train_path: ../data/{0}/Train.tsv
    validation_path: ../data/{0}/Val.tsv
    test_path: ../data/{0}/Test.tsv
    side_information:
      - dataloader: WordsTextualAttributesPreprocessed
        all_item_texts: ../data/{0}/all_item_texts.npy
        all_user_texts: ../data/{0}/all_user_texts.npy
        embed_vocabulary: ../data/{0}/embed_vocabulary.npy
        item_to_user: ../data/{0}/item_to_user.npy
        item_to_user_to_item: ../data/{0}/item_to_user_to_item.npy
        user_to_item: ../data/{0}/user_to_item.npy
        user_to_item_to_user: ../data/{0}/user_to_item_to_user.npy
  dataset: Digital_Music
  top_k: 20
  evaluation:
    cutoffs: [20]
    simple_metrics: [Recall, MSE]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.RMG:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        save_recs: False
        validation_rate: 1
        validation_metric: MSE
        restore: False
      lr: [0.0001, 0.0005, 0.001, 0.005, 0.01]
      dropout: 0.2
      epochs: 50
      loader: ('WordsTextualAttributesPreprocessed',)
      batch_size: 128
      seed: 123
#    external.MF:
#      meta:
#        hyper_opt_alg: grid
#        verbose: True
#        save_weights: False
#        save_recs: False
#        validation_rate: 1
#        validation_metric: MSE
#        restore: False
#      epochs: 50
#      batch_size: 128
#      factors: 16
#      lr: [0.0001, 0.0005, 0.001, 0.005, 0.01]
#      seed: 123
#    external.NCF:
#      meta:
#        hyper_opt_alg: grid
#        verbose: True
#        save_weights: False
#        save_recs: False
#        validation_rate: 1
#        validation_metric: MSE
#        restore: False
#      epochs: 50
#      batch_size: 128
#      factors: 16
#      lr: [0.0001, 0.0005, 0.001, 0.005, 0.01]
#      dropout: 0.1
#      dense_size: (32,16,8)
#      seed: 123
#    external.GCMC:
#      meta:
#        save_recs: False
#        validation_metric: MSE
#        validation_rate: 1
#        verbose: True
#      epochs: 50
#      batch_size: 128
#      factors: 32
#      lr: [0.0001, 0.0005, 0.001, 0.005, 0.01]
#      conv_size: 32
#      dense_size: 32
#      n_conv: 1
#      n_dense: 1
#      relations: (1,2,3,4,5)
#      num_basis: 2
#      dropout: 0.1
#      acc: stack
#      seed: 123
#    external.EGCF:
#      meta:
#        hyper_opt_alg: grid
#        verbose: True
#        save_weights: False
#        save_recs: False
#        validation_rate: 1
#        validation_metric: MSE
#        restore: False
#      epochs: 50
#      batch_size: 128
#      lr: [0.0001, 0.0005, 0.001, 0.005, 0.01]
#      n_layers: [1, 2, 3, 4]
#      emb: [8, 16, 32]
#      loader: ('InteractionsTextualAttributes',)
#      seed: 123